### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by gregoryyoung** [alexeyzimarev/CsharpPatternMatching#1]
I am not a big fan of this:

https://github.com/alexeyzimarev/CsharpPatternMatching/blob/master/NewStuff/Customer.cs#L17

The reason why is though it will work in this trivial case it won't work in many other cases. As example what about dependencies? Also how will you handle a case such as EnrollStudentInClass where you need to pass the Student as a parameter?

**Comment by alexeyzimarev** [comment]
I know that this is oversimplified. Proto.Actor uses [similar approach](https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/examples/Chat/Server/Program.cs#L18) for handling commands and this is not always working in case you need more complex dependencies. Tbh my point was more to show pattern matching in projections, where it always work since projections need no dependencies and only deal with data included in the event.

**Comment by gregoryyoung** [comment]
That's fair. For the domain object side I much prefer to have the command handler as it is a convenient place for handling the dependency resolution (which I prefer to keep out of the actual domain objects eg the command handler passes them forward).

**Comment by RagingKore** [comment]
Just delete it @alexeyzimarev lol
Pattern matching works well for apply just like we did it here @gregoryyoung https://github.com/UbiquitousAS/WorkshopEventSourcing/blob/master/final/src/Marketplace.Domain/ClassifiedAds/ClassifiedAd.cs

**Comment by RagingKore** [comment]
The App Service or Command Handler will get the dependencies via Ctor and pass them on to the aggregate method.

**Comment by gregoryyoung** [comment]
Pattern matching does work well for apply (have done in other languages such as erlang previously)

**Comment by alexeyzimarev** [comment]
The Apply with pattern matching is what Sergio is pointing to in our workshop sample. Also it is the same for projections. We did handling of commands in the application service, which then calls the aggregate methods.

**Comment by alexeyzimarev** [comment]
But again since we have one application service class to handle all commands, it might have too many dependencies and this is what we were having disagreements about. I guess this is different case by case. https://github.com/UbiquitousAS/WorkshopEventSourcing/blob/master/final/src/Marketplace/Api/ClassifiedAdsApplicationService.cs

**Comment by alexeyzimarev** [comment]
@RagingKore I don't want to delete it for the sake of getting back here when I talk to people who prefer having command-handling aggregates (or entities, whatever). As you know, in [Eventuous](https://github.com/Eventuous/eventuous) it's done right (or, "looks and feels right to me") :)
